name: Continuous Integration for Job Data Pipeline

on:
    push:
        branches: ["feat/**", "fix/**"]
        paths:
            - "src/**"
            - "tests/**"
            - "poetry.lock"
            - "pyproject.toml"
    pull_request:
        branches: [dev]
        paths:
            - "src/**"
            - "tests/**"
            - "poetry.lock"
            - "pyproject.toml"

    workflow_dispatch:
        #  cuma test dan lint, tidak deployment, karena deployment sudah ada di cd.yml

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "poetry"
            - name: Install dependencies
              run: |
                  python -m pip install poetry
                  poetry install --with dev

            - name: Lint code with ruff
              run: |
                  poetry run ruff format --check src tests
                  poetry run ruff check src tests

            - name: Type check with mypy
              run: poetry run mypy src tests

            - name: Run tests
              run: poetry run pytest --tb=short
